# Generated by Django 4.0 on 2026-05-02 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('start_date', models.CharField(max_length=500)),
                ('end_date', models.DateField()),
                ('exam_date', models.DateField()),
                ('status', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.session'),
        ),
    ]
