# Generated by Django 4.0 on 2026-05-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_session_student_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('6_months', '6 Months'), ('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years')], max_length=20),
        ),
    ]
