# Generated by Django 4.0 on 2026-05-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cert_type',
            field=models.CharField(choices=[('course', 'Course Certificate'), ('it_program', 'IT Program Certificate'), ('both', 'Both (Course + IT Program)')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
