# Generated by Django 4.0 on 2026-05-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_course_cert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
