# Generated by Django 4.0 on 2026-05-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_session_name_alter_session_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='branch_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
