# Generated by Django 4.0 on 2026-05-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_student_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Bangladeshi', 'Bangladeshi'), ('Indian', 'Indian'), ('Pakistani', 'Pakistani'), ('Nepali', 'Nepali'), ('Sri Lankan', 'Sri Lankan'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
