# Generated by Django 4.0 on 2026-05-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.session'),
            preserve_default=False,
        ),
    ]
