# Generated by Django 4.0 on 2026-05-07 20:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_certificate_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('trx_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('extra_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gateway', models.CharField(default='bkash', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('raw_create_response', models.JSONField(blank=True, null=True)),
                ('raw_execute_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_deposits', to='accounts.user')),
            ],
        ),
    ]
