# Generated by Django 4.0 on 2026-05-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_paymentdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sign_image',
            field=models.ImageField(blank=True, default='sign_images/default.png', null=True, upload_to='sign_images/'),
        ),
    ]
