# Generated by Django 4.0 on 2026-05-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_sign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='thana',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
