# Generated by Django 4.0 on 2026-05-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_student_district_student_thana'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, default='qr_images/default.png', null=True, upload_to='qr_images/'),
        ),
    ]
