# Generated by Django 4.0 on 2026-05-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_certificate_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_image', models.ImageField(blank=True, null=True, upload_to='sign_images/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
