# Generated by Django 4.0 on 2026-05-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_chairman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='sign_image',
            field=models.ImageField(blank=True, null=True, upload_to='chairman_images/'),
        ),
    ]
