# Generated by Django 4.0 on 2026-05-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_chairman_sign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='admitcard_bg',
            field=models.ImageField(default='chairman_images/admitcard.jpeg', upload_to='chairman_images/'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='certificate_bg',
            field=models.ImageField(default='chairman_images/certnew22.jpeg', upload_to='chairman_images/'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='idcard_bg',
            field=models.ImageField(default='chairman_images/student-card.jpeg', upload_to='chairman_images/'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='registration_bg',
            field=models.ImageField(default='chairman_images/Regi.jpeg', upload_to='chairman_images/'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='sign_image',
            field=models.ImageField(default='chairman_images/sign.png', upload_to='chairman_images/'),
        ),
    ]
